project_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('telemart/', include('telemart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

telemart/urls.py
from django.urls import path
from . import views

app_name = 'telemart'

urlpatterns = [
    path('', views.index, name='index'),
    path('company/all/', views.CompanyListView.as_view(), name='company-list'),
    path('company/<int:pk>/', views.CompanyDetailView.as_view(), name='company-detail'),
    path('product/all/', views.ProductListView.as_view(), name='product-list'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='wishlist-add'),
    path('wishlist/rmv/<int:product_id>/', views.remove_from_wishlist, name='wishlist-rmv'),
    path('search/match/', views.search, name='search'),
    path('logout/user/', views.logout_user, name='logout-user'),
    path('login/page/', views.login_page, name='login-page'),
    path('login/user/', views.login_user, name='login-user'),
    path('comment/add/<int:product_id>/', views.add_comment, name='add-comment'),
    path('add/company/new', views.add_new_company, name='add-new-company'),
    path('add/product/new', views.add_new_product, name='add-new-product'),
    path('settings/config/', views.config, name='config'),
    # API
    path('api/product/all/', views.ProductListAPIView.as_view(), name='api-product-list')
]

telemart/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

import random

from sympy.multipledispatch.conflict import ordering

class Company(models.Model):
    name = models.CharField(max_length=128)
    icon = models.ImageField(upload_to='companies/', null=True, blank=True)
    description = models.FileField(upload_to='company_descriptions/', null=True, blank=True)
    official = models.CharField(max_length=56, null=True, blank=True)
    trailer = models.CharField(max_length=11, null=True, blank=True)
    # products

    def __str__(self):
        return self.name

    def url(self):
        return reverse('telemart:company-detail', kwargs={'pk': self.id})

    def power(self):
        products = self.products.all()
        if products:
            return sum(p.power for p in products) / len(products)
        return 0.0

    class Meta:
        ordering = ['-name']


class Product(models.Model):
    title = models.CharField(max_length=128)
    year = models.IntegerField(null=True, blank=True)
    power = models.FloatField(default=4.0)
    picture = models.ImageField(upload_to='products/', null=True, blank=True)
    description = models.FileField(upload_to='product_descriptions/', null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL,
                                 null=True, blank=True, related_name='products')
    trailer = models.CharField(max_length=11, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    fans = models.ManyToManyField(User, related_name='product_wishlist', blank=True)
    hotline = models.CharField(max_length=56, null=True, blank=True)
    # comments

    def __str__(self):
        return self.title

    def url(self):
        return reverse('telemart:product-detail', kwargs={'slug': self.slug})


class UserAddon(models.Model):
    user = models.OneToOneField(User, related_name='addon', on_delete=models.CASCADE)
    userpic = models.ImageField(upload_to='userpics/', null=True, blank=True)

    def __str__(self):
        return f'{self.user}\' addon'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.text} ({self.product})'

    class Meta:
        ordering = ['-published']

telemart/forms.py
from django import forms

from .models import *


class CommentForm(forms.Form):
    text = forms.CharField(label='Type here',
                           widget=forms.TextInput(attrs={'placeholder': 'Ваш отзыв'}))


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'year', 'power', 'picture',
                  'description', 'company', 'trailer', 'hotline']

telemart/views.py
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics

from .serializers import *
from .models import *
from .forms import *

def index(request):
    context = {
        'best_products': Product.objects.order_by('-power')[:4],
        'companies': Company.objects.order_by('-name')[:4],
        'gpus': Product.objects.filter(company__name='NVIDIA').order_by('-power')[:4],
        'cpus': Product.objects.filter(Q(company__name='AMD') | Q(company__name='Intel')).order_by('-power')[:2],
        'motherboards': Product.objects.filter(company__name='MSI').order_by('-power'),
        'memory': Product.objects.filter(company__name='HyperX'),
        'pus': Product.objects.filter(Q(company__name='Chieftec') | Q(company__name='Deepcool')),
    }
    return render(request, template_name='telemart/index.html',
                  context=context)


class CompanyListView(ListView):
    model = Company


class CompanyDetailView(DetailView):
    model = Company
    # login_url = reverse_lazy('imdb:login-page')


class ProductListView(ListView):
    model = Product
    queryset = Product.objects.all().order_by('-title')
    paginate_by = 12


class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'comment_form': CommentForm(),
    }


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('telemart:index'))


def login_page(request):
    context = {}
    if 'next' in request.GET:
        context['next'] = request.GET['next']
    return render(request, template_name='telemart/login_page.html',
                  context=context)


def login_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    next = request.POST.get('next')
    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
        if next:
            return HttpResponseRedirect(next)
        else:
            return HttpResponseRedirect(reverse('telemart:index'))
    else:
        context = {'message': 'Incorrect username or password. Try again'}
        if next:
            context['next'] = next
        return render(request, template_name='telemart/login_page.html',
                      context=context)


def search(request):
    match = request.POST.get('match')
    if match:
        company_list = Company.objects.filter(name__icontains=match)
        product_list = Product.objects.filter(title__icontains=match)
        context = {
            'match': match,
            'company_list': company_list,
            'product_list': product_list,
        }
        return render(request, template_name='telemart/search.html',
                      context=context)
    else:
        return HttpResponseRedirect(reverse('telemart:index'))


def add_to_wishlist(request, product_id):
    user = request.user
    product = Product.objects.get(pk=product_id)
    user.product_wishlist.add(product)
    return HttpResponseRedirect(reverse('telemart:product-detail',
                                kwargs={'slug': product.slug}))


def remove_from_wishlist(request, product_id):
    user = request.user
    product = Product.objects.get(pk=product_id)
    user.product_wishlist.remove(product)
    return HttpResponseRedirect(reverse('telemart:product-detail',
                                        kwargs={'slug': product.slug}))


def add_comment(request, product_id):
    user = request.user
    product = Product.objects.get(pk=product_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        text = form.cleaned_data.get('text')
        new_comment = Comment(author=user, product=product,
                              text=text)
        new_comment.save()
    return HttpResponseRedirect(reverse('telemart:product-detail',
                                        kwargs={'slug': product.slug}))


def config(request):
    context = {
        'company_form': CompanyForm(),
        'product_form': ProductForm(),
    }
    return render(request, template_name='telemart/config.html',
                  context=context)

def add_new_company(request):
    form = CompanyForm(request.POST)
    if form.is_valid():
        new_company = form.save(commit=False)
        if 'icon' in request.FILES:
            new_company.portrait = request.FILES['icon']
        new_company.save()
    return HttpResponseRedirect(reverse('telemart:company-list'))


def add_new_product(request):
    form = ProductForm(request.POST)
    if form.is_valid():
        new_product = form.save(commit=False)
        if 'picture' in request.FILES:
            new_product.picture = request.FILES['picture']
        if 'description' in request.FILES:
            new_product.description = request.FILES['description']
        slug = '-'.join(p.lower() for p in new_product.title.split()) \
               + f'-{new_product.power}'
        new_product.slug = ''.join(c for c in slug if c.isalpha() or c.isdigit() or c == '-')
        new_product.save()
        form.save_m2m()
    return HttpResponseRedirect(reverse('telemart:product-list'))


class ProductListAPIView(generics.ListAPIView):
    queryset = Product.objects.order_by('-power')
    serializer_class = MovieSerializer1

telemart/templates/telemart/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'telemart/css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'telemart/img/icon.png' %}" type="image/x-icon">
</head>
<body class="bg-light">
    <div class="container">
        <div class="row my-3 justify-content-between">
            <div class="col-2">
                <a href="{% url 'telemart:index' %}">
                    <img src="{% static 'telemart/img/logo.svg' %}" class="w-100 mt-4">
                </a>
            </div>
            <div class="col-6 text-center">
                <a href="{% url 'telemart:product-list' %}">
                    <h4 class="text-dark text-muted">Все товары</h4>
                </a>
                <hr>
                <form action="{% url 'telemart:search' %}" method="post" class="pt-1">
                    {% csrf_token %}
                    <input type="text" name="match" placeholder="Поиск по всему сайту"
                    class="form-control">
                </form>
            </div>
            <div class="col-3">
                <p class="text-dark">
                    {% if user.is_authenticated %}
                    <img src="{{ user.addon.userpic.url }}" width="50">
                    <br>
                    {{ user.username }}
                        {% if user.is_staff %}
                        <a href="#">
                            <img src="#" width="15">
                        </a>
                        {% endif %}
                    <br>
                    <a href="#" class="text-success text-decoration-underline">
                        <img src="#" width="20">Выйти
                    </a>
                    {% else %}
                    <a href="#" class="text-success text-decoration-underline">
                        <img src="#" width="20">Войти
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

telemart/templates/telemart/company_detail.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
{{ object }} - Telemart
{% endblock %}

{% block content %}

<h3 class="text-muted">{{ object }}</h3>


<div class="row justify-content-between">
    <div class="col-3">
        {% if company.official %}
        <a href="https://{{ company.official }}" class="text-success text-decoration-underline" target="_blank">Visit official page</a>
        {% endif %}
        <h4 class="text-muted text-start my-2">
            <img src="{% static 'telemart/img/star.png' %}" width="17">
        {{ object.power|floatformat:1 }}/10</h4>
    </div>
</div>

<div class="row my-3 justify-content-between">
    <div class="col-3">
        <img src="{{ company.icon.url }}" class="img-fluid rounded w-100 h-100">
    </div>
    <div class="col-9">
        {% if company.description %}
        <p class="text-dark">
            {{ company.description.read.decode }}
        </p>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-3">
        <h3 class="text-dark">{{ object.name }}'s products</h3>

        {% for product in company.products.all|dictsortreversed:"power" %}
        <div class="row mt-4">
                <a href="{{ product.url }}">
                    <h5 class="text-dark">{{ product.title }}</h5>
                </a>
        </div>
        {% endfor %}
    </div>
    <div class="col-6">
        {% if company.trailer %}
        <iframe width="1024" height="768" src="https://www.youtube.com/embed/{{ company.trailer }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {% endif %}
    </div>
</div>


{% endblock %}

telemart/templates/telemart/company_list.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Компании - Telemart
{% endblock %}

{% block content %}

<h3 class="text-muted">Все компании</h3>

<div class="row mt-3">
    {% for company in object_list %}
    <div class="col-3 text-center">
        <a href="{{ company.url }}">
            <img src="{{ company.icon.url }}" class="w-75 h-75 rounded ms-9">
        </a>
        <a href="{{ company.url }}">
            <h5 class="text-muted p-3 mt-2">Товары: {{ company.products.all|length }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

{% endblock %}

telemart/templates/telemart/config.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Add content - Telemart
{% endblock %}

{% block content %}

<h3 class="text-muted">Add content</h3>
<h5 class="text-danger">(only for admin)</h5>

<div class="row justify-content-between mt-5">
    <div class="col-5">
        <h4 class="text-dark">Добавить компанию</h4>
        <form action="{% url 'telemart:add-new-company' %}" method="post" 
        class="text-dark" enctype="multipart/form-data">
            {% csrf_token %}
            {{ company_form.as_p }}
            {% if user.is_superuser %}
            <input type="submit" value="Добавить" class="btn btn-success">
            {% endif %}
        </form>
    </div>
    <div class="col-7">
        <h4 class="text-dark">Добавить товар</h4>
        <form action="{% url 'telemart:add-new-product' %}" method="post" 
        class="text-secondary" enctype="multipart/form-data">
            {% csrf_token %}
            {{ product_form.as_p }}
            {% if user.is_superuser %}
            <input type="submit" value="Добавить" class="btn btn-success">
            {% endif %}
        </form>
        
    </div>
</div>

{% endblock %}

telemart/templates/telemart/index.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Интернет-магазин Telemart - магазин комплектующих для ПК
{% endblock %}

{% block content %}

<h3 class="text-dark text-muted">Сейчас популярно</h3>

<div class="row mt-3">
    {% for product in best_products %}
    <div class="col-3 text-center">
        <a href="{{ product.url }}">
            <img src="{{ product.picture.url }}" class="h-50 w-75 rounded">
        </a>
        <h4 class="text-dark text-start ms-5">
            <img src="{% static 'telemart/img/star.png' %}" width="17">
        {{ product.power }}</h4>
        <a href="{{ product.url }}">
            <h5 class="text-dark text-start ms-5">{{ product.company }}</h5>
            <h5 class="text-dark text-start ms-5">{{ product.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

<hr>

<a href="{% url 'telemart:company-list' %}">
    <h3 class="text-dark text-muted">Компании изготовители</h3>
</a>

<div class="row mt-3">
    {% for company in companies %}
    <div class="col-3 text-center">
        <a href="{{ company.url }}">
            <img src="{{ company.icon.url }}" class="w-75 h-75 rounded">
        </a>
        <a href="{{ company.url }}">
            <h5 class="text-dark text-start ms-5 mt-3">{{ company.name }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

<hr>


<h3 class="text-dark text-muted">Видеокарты</h3>

<div class="row mt-3">
    {% for gpu in gpus %}
    <div class="col-3 text-center">
        <a href="{{ gpu.url }}">
            <img src="{{ gpu.picture.url }}" class="w-50 h-50 rounded">
        </a>
        <a href="{{ gpu.url }}">
            <h5 class="text-dark text-start ms-3 mt-2">{{ gpu.company }}</h5>
            <h5 class="text-dark text-start ms-3 mt-3">{{ gpu.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

<hr>


<h3 class="text-dark text-muted">Процессоры</h3>

<div class="row mt-3">
    {% for cpu in cpus %}
    <div class="col-3 text-center">
        <a href="{{ cpu.url }}">
            <img src="{{ cpu.picture.url }}" class="w-50 h-50 rounded">
        </a>
        <a href="{{ cpu.url }}">
            <h5 class="text-dark text-start ms-3 mt-2">{{ cpu.company }}</h5>
            <h5 class="text-dark text-start ms-3 mt-3">{{ cpu.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

<hr>


<h3 class="text-dark text-muted">Мат. платы</h3>

<div class="row mt-3 my-2">
    {% for mb in motherboards %}
    <div class="col-3 text-center">
        <a href="{{ mb.url }}">
            <img src="{{ mb.picture.url }}" class="w-50 h-75 rounded">
        </a>
        <a href="{{ mb.url }}">
            <h5 class="text-dark text-start ms-3 mt-2">{{ mb.company }}</h5>
            <h5 class="text-dark text-start ms-3 mt-3">{{ mb.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>


<hr class="mb-3">


<h3 class="text-dark text-muted">ОЗУ</h3>

<div class="row mt-3 my-2">
    {% for m in memory %}
    <div class="col-3 text-center">
        <a href="{{ m.url }}">
            <img src="{{ m.picture.url }}" class="w-50 h-75 rounded">
        </a>
        <a href="{{ m.url }}">
            <h5 class="text-dark text-start ms-3 mt-2">{{ m.company }}</h5>
            <h5 class="text-dark text-start ms-3 mt-3">{{ m.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>

<hr class="mt-3">


<h3 class="text-dark text-muted my-2">Блоки питания</h3>

<div class="row mt-3 my-2">
    {% for pu in pus %}
    <div class="col-3 text-center">
        <a href="{{ pu.url }}">
            <img src="{{ pu.picture.url }}" class="w-50 h-75 rounded">
        </a>
        <a href="{{ pu.url }}">
            <h5 class="text-dark text-start ms-3 mt-2">{{ pu.company }}</h5>
            <h5 class="text-dark text-start ms-3 mt-3">{{ pu.title }}</h5>
        </a>
    </div>
    {% endfor %}
</div>


{% endblock %}

telemart/templates/telemart/login_page.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Login - Telemart
{% endblock %}

{% block content %}
<h3 class="text-light">Авторизация</h3>


<form action="{% url 'telemart:login-user' %}" method="POST">
    {% csrf_token %}
    <form>
        <!-- Email input -->
        <div class="form-outline mb-4">
          <input type="email" id="form2Example1" class="form-control" />
          <label class="form-label" for="form2Example1">Email address</label>
        </div>
      
        <!-- Password input -->
        <div class="form-outline mb-4">
          <input type="password" id="form2Example2" class="form-control" />
          <label class="form-label" for="form2Example2">Password</label>
        </div>
      
        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
              <label class="form-check-label" for="form2Example31"> Remember me </label>
            </div>
          </div>
      
          <div class="col">
            <!-- Simple link -->
            <a href="#!">Forgot password?</a>
          </div>
        </div>
      
        <!-- Submit button -->
        <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button>
      
        <!-- Register buttons -->
        <div class="text-center">
          <p>Not a member? <a href="#!">Register</a></p>
          <p>or sign up with:</p>
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-facebook-f"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-google"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-twitter"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-github"></i>
          </button>
        </div>
      </form>
</form>



{% endblock %}

telemart/templates/telemart/product_detail.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
{{ product.title }} - Telemart
{% endblock %}

{% block content %}

<h3 class="text-muted">{{ product.title }}</h3>


<div class="row my-2 justify-content-between">
    <div class="col-2"> 
        <h4 class="text-dark text-start ms-6 mb-2">
            <img src="{% static 'telemart/img/star.png' %}" width="17">
        {{ product.power }}/10</h4>
        {% if user.is_authenticated %}
            {% if user not in product.fans.all %}
                <a href="{% url 'telemart:wishlist-add' product.id %}"
                class="btn btn-outline-success">
                    + В список желаемого
                </a>
            {% else %}
                <a href="{% url 'telemart:wishlist-rmv' product.id %}" 
                class="btn btn-outline-success">✓ Убрать из списка</a>
            {% endif %}
        {% endif %}
    </div>
</div>

<div class="row my-3 justify-content-between">
    <div class="col-3">
        <img src="{{ product.picture.url }}" class="img-fluid rounded">
        <a href="{{ product.company.url }}">
            <h3 class="text-dark mb-2">{{ product.company }}</h3>
        </a>

        {% if product.description %}
        <p class="text-dark">
            {{ product.description.read.decode }}
        </p>
        {% endif %}
        {% if product.hotline %}
            <a href="https://hotline.ua/ua/sr/?q={{ product.hotline }}" class="text-success text-decoration-underline ms-5"
            target="_blank">
                <img src="{% static 'telemart/img/goto.png' %}" width="13">
            Смотреть на Hotline</a>
        {% endif %}

    </div>
    <div class="col-9">
        {% if product.trailer %}
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ product.trailer }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {% endif %}

        <h3 class="text-dark">Отзывы</h3>
        {% for comment in product.comments.all %}
        <p class="text-dark">
            <img src="{{ comment.author.addon.userpic.url }}" width="35">
            {{ comment.author }}: {{ comment.text }}
            <span class="text-secondary">{{ comment.published|timesince }}</span>
        </p>
        {% empty %}
        <p class="text-dark">Оставь первый отзыв</p>
        {% endfor %}

        {% if user.is_authenticated %}
            {% if user.is_staff %}
            <form action="{% url 'telemart:add-comment' product.id %}" 
            method="post" class="text-dark">
                {% csrf_token %}
                {{ comment_form }}
                <input class="btn btn-outline-success" type="submit" value="Добавить">
            </form>
            {% endif %}
        {% endif %}

    </div>
</div>

{% endblock %}

telemart/templates/telemart/product_list.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Все товары - Telemart
{% endblock %}

{% block content %}

<h3 class="text-muted">Все товары</h3>



<div class="row">
    {% for prod in object_list %}
    <div class="col-3 text-center mt-3">
        <a href="{{ prod.url }}">
            <img src="{{ prod.picture.url }}" class="h-50 w-50 rounded">
        </a>
        <h5 class="text-secondary text-start ms-5">
            <img src="{% static 'telemart/img/star.png' %}" width="17">
        {{ prod.power }}</h5>
        <a href="{{ prod.url }}">
            <h5 class="text-dark text-start ms-5">{{ prod.company }}</h5>
            <h5 class="text-dark text-start ms-5">{{ prod.title }}</h5>
        </a>
        {% if prod.hotline %}
            <a href="https://hotline.ua/ua/sr/?q={{ prod.hotline }}" class="text-dark m-2"
            target="_blank">
                <img src="{% static 'telemart/img/goto.png' %}" width="13">
            Смотреть на Hotline</a>
        {% endif %}
    </div>
    {% endfor %}
</div>

<div class="row mt-5 justify-content-center ms-5">
    <div class="col-2 text-dark">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="text-dark"><img src="{% static 'telemart/img/prev.png' %}" width="15"></a>
        {% endif %}
    </div>
    <div class="col-2 text-dark">
        <p>{{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</p>
    </div>
    <div class="col-2 text-dark">
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="text-dark"><img src="{% static 'telemart/img/next.png' %}" width="15"></a>
        {% endif %}
    </div>
</div>

{% endblock %}

telemart/templates/telemart/search.html
{% extends 'telemart/base.html' %}
{% load static %}

{% block title %}
Search by "{{ match }}" - Telemart
{% endblock %}

{% block content %}

<h2 class="text-secondary"></h2>

<h2 class="text-muted">Поиск по запросу "{{ match }}"</h2>

<h4 class="text-dark">Товары ({{ product_list|length }}):</h4>

{% for prod in product_list %}
<div class="row my-2">
    <div class="col-2 my-3">
        <img src="{{ prod.picture.url }}" class="w-75">
    </div>
    <div class="col-4">
        <a href="{{ prod.url }}">
            <h4 class="text-dark">{{ prod }}</h4>
            <p class="text-dark">{{ prod.company }}</p>
        </a>
    </div>
</div>
{% endfor %}

<h4 class="text-dark">Компании ({{ company_list|length }}):</h4>

{% for c in company_list %}
<div class="row my-2">
    <div class="col-2 my-3">
        <img src="{{ c.icon.url }}" class="img-fluid rounded">
    </div>
    <div class="col-4 my-3">
        <a href="{{ c.url }}">
            <h4 class="text-dark">{{ c.name }}</h4>
            <p class="text-dark">Товары: {{ c.products.all|length }}</p>
        </a>
    </div>
</div>
{% endfor %}

{% endblock %}